In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4]
a=np.array(lst)

In [3]:
# one dimensional array
a.shape

(4,)

In [4]:
b=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=np.array(b)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
# shows rows and columns
b.shape

(4, 3)

In [6]:
b.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
# minimum dimension,ndmin
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [8]:
b.shape

(4, 3)

In [9]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
b[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [11]:
b[1:3,[0,2]]

array([[4, 6],
       [7, 9]])

In [12]:
b[[0,3],[0,2]]

array([ 1, 12])

In [13]:
a=np.matrix([[1, 2], [3, 4]])
a

matrix([[1, 2],
        [3, 4]])

In [14]:
# 1d array
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [15]:
# 2d array
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
type(a)

numpy.ndarray

In [17]:
a.ndim

1

In [18]:
c.ndim

2

In [19]:
a.shape

(3,)

In [20]:
c.shape

(2, 3)

In [21]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
# no. of elements in array
c.size

6

In [23]:
c.dtype

dtype('int32')

In [24]:
d=np.zeros((3,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#array with random values
e=np.random.random((2,2))
e

array([[0.43477438, 0.42794477],
       [0.59235361, 0.59394074]])

In [26]:
f=np.arange(0,35,10)
f

array([ 0, 10, 20, 30])

In [27]:
arr=np.array([[-1,2,0,4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],
              [3, -7, 4, 2.0]])
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [28]:
x=arr[:2,[0,2]]
x

array([[-1.,  0.],
       [ 4.,  6.]])

In [29]:
b=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=np.array(b)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
# transpose of a matrix
b.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [31]:
x=np.array([1,2])
x-1

array([0, 1])

In [32]:
y=np.array([[1,2],[3,4]])
y+1

array([[2, 3],
       [4, 5]])

In [33]:
arr=np.linspace(0,50,5)
arr

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [34]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
arr

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 9]])

In [35]:
arr.max()

9

In [36]:
# column wise maximum element
arr.max(axis=0)

array([4, 7, 9])

In [37]:
# row wise maximum element 
arr.max(axis=1)

array([6, 7, 9])

In [38]:
c=np.array([2,3])
d=np.array([8,9])
e=np.sum([c,d],axis=0)
e

array([10, 12])

In [39]:
f=np.sum([c,d],axis=1)
f

array([ 5, 17])

In [40]:
a = np.array([[1,2],[3,4]])
b = np.array([[5, 6],[7, 8]])
print(a)    
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [41]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [42]:
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [43]:
print(np.column_stack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
print(np.concatenate((a,b),axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [46]:
m = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
m

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [47]:
# rank of a matrix
np.linalg.matrix_rank((m))

3

In [48]:
# solve linear equation
# x+2*y=8
# 3*x+4*y=18
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([8,18])
print(np.linalg.solve(a,b))

[2. 3.]
